alias midway='ssh -X dmasson@midway2-login2.rcc.uchicago.edu'
alias tunnel_midway='ssh -N -f -L localhost:19666:localhost:19666 dmasson@midway2-login2.rcc.uchicago.edu'
alias cunnilingus='ssh masson@cunn1.lngs.infn.it'

alias l='ls -Ahl --color=auto --group-directories-first'
alias ls='ls --color=auto --group-directories-first'
alias ll='ls -laX --color=auto --group-directories-first'

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias sed='sed -r'
alias diff='diff --color=auto --side-by-side --expand-tabs --initial-tab --tabsize=4 --ignore-all-space'

alias ..='cd ..'
alias ce='cd'
alias ced='cd'
alias rm='rm -I -v'
alias cp='cp -i -v --preserve=mode,ownership,timestamps'
alias mv='mv -v'
alias chomd='chmod'
alias scp='scp -p'

alias vch='amixer sset Master'
alias de='setxkbmap de'
alias us='setxkbmap us'
